import pymysql 
SONIK={
    '종목코드'                         : 'STKCODE',
    '날짜'                         : 'DATE',
    '보고서종류'                       : 'REPORT',
    '매출액'                          :   'REV',
    '매출원가'                        :   'CGS',
    '매출총이익'                       :   'GROSS',
    '판매비와관리비'                   :   'SGA',
    '판매비와관리비_인건비'             :  'SGA_1',
    '판매비와관리비_유무형자산상각비'    :  'SGA_2',
    '판매비와관리비_연구개발비'         :   'SGA_3',
    '판매비와관리비_광고선전비'         :   'SGA_4',
    '판매비와관리비_판매비'             :   'SGA_5',
    '판매비와관리비_관리비'             :   'SGA_6',
    '판매비와관리비_기타원가성비용'      :  'SGA_7',
    '판매비와관리비_기타'               :   'SGA_8',
    '영업이익'                         :   'OPR',
    '영업이익(발표기준)'                :   'OPR_',
    '금융수익'                                        :    'FININC',
    '금융수익_이자수익'                                :   'FINNIC_1',
    '금융수익_배당금수익'                              :   'FINNIC_2',
    '금융수익_외환이익'                                :   'FINNIC_3',
    '금융수익_대손충당금환입액'                         :   'FINNIC_4',
    '금융수익_매출채권처분이익'                         :   'FINNIC_5',
    '금융수익_당기손익-공정가치측정 금융자산관련이익'     :   'FINNIC_6',
    '금융수익_금융자산처분이익'                         :   'FINNIC_7',
    '금융수익_금융자산평가이익'                         :   'FINNIC_8',
    '금융수익_금융자산손상차손환입'                     :   'FINNIC_9',
    '금융수익_파생상품이익'                             :   'FINNIC_10',
    '금융수익_기타금융수익'                             :   'FINNIC_11',
    '금융원가'                                      :   'FINCOST',
    '금융원가_이자비용'                              :   'FINCOST_1',
    '금융원가_외환손실'                              :   'FINCOST_2',
    '금융원가_대손상각비'                            :   'FINCOST_3',
    '금융원가_당기손익-공정가치측정 금융자산관련손실'   :   'FINCOST_4',
    '금융원가_매출채권처분손실'                      :   'FINCOST_5',
    '금융원가_금융자산처분손실'                       :   'FINCOST_6',
    '금융원가_금융자산평가손실'                       :   'FINCOST_7',
    '금융원가_금융자산손상차손'                       :   'FINCOST_8',
    '금융원가_파생상품손실'                           :   'FINCOST_9',
    '금융원가_기타금융원가'                           :   'FINCOST_10',
    '기타수익'                                    :   'OTHERREV',
    '기타수익_이자수익'                            :   'OTHERREV_1',
    '기타수익_배당금수익'                          :   'OTHERREV_2',
    '기타수익_외환이익'                            :   'OTHERREV_3',
    '기타수익_재고자산감모손실환입'                  :   'OTHERREV_4',
    '기타수익_재고자산폐기(처분)이익'                :   'OTHERREV_5',
    '기타수익_당기손익-공정가치측정 금융자산평가이익' :   'OTHERREV_6',
    '기타수익_자산처분(폐기)이익'                   :   'OTHERREV_7',
    '기타수익_자산평가이익'                         :   'OTHERREV_8',
    '기타수익_자산손상차손환입'                     :   'OTHERREV_9',
    '기타수익_파생상품이익'                         :   'OTHERREV_10',
    '기타수익_임대료수익'                           :   'OTHERREV_11',
    '기타수익_로열티수익'                           :   'OTHERREV_12',
    '기타수익_수수료수익'                           :   'OTHERREV_13',
    '기타수익_대손충당금환입'                       :   'OTHERREV_14',
    '기타수익_충당부채환입액'                       :   'OTHERREV_15',
    '기타수익_기타'                                 :   'OTHERREV_16',
    '기타비용'                                          :   'OTHERCOST',
    '기타비용_이자비용'                                  :   'OTHERCOST_1',
    '기타비용_외환손실'                                  :   'OTHERCOST_2',
    '기타비용_재고자산감모손실'                           :   'OTHERCOST_3',
    '기타비용_재고자산폐기(처분)손실'                     :   'OTHERCOST_4',
    '기타비용_당기손익-공정가치측정 금융자산평가손실'       :   'OTHERCOST_5',
    '기타비용_자산처분(폐기)손실'                         :   'OTHERCOST_6',
    '기타비용_자산평가손실'                               :   'OTHERCOST_7',
    '기타비용_자산손상차손'                               :   'OTHERCOST_8',
    '기타비용_파생상품손실'                               :   'OTHERCOST_9',
    '기타비용_기타대손상각비'                             :   'OTHERCOST_10',
    '기타비용_충당부채전입액'                             :   'OTHERCOST_11',
    '기타비용_기타'                                      :   'OTHERCOST_12',
    '종속기업,공동지배기업및관계기업관련손익'                                                              :   'OTHERRPL',
    '종속기업,공동지배기업및관계기업관련손익_지분법손익'                                                    :   'OTHERRPL_1',
    '종속기업,공동지배기업및관계기업관련손익_종속기업,공동지배기업및관계기업투자주식처분손익'                   :   'OTHERRPL_2',
    '종속기업,공동지배기업및관계기업관련손익_종속기업,공동지배기업및관계기업투자주식손상관련손익'               :   'OTHERRPL_3',
    '종속기업,공동지배기업및관계기업관련손익_ 기타'                                                         :   'OTHERRPL_4',
    '세전계속사업이익'       :   'EBIT',
    '법인세비용'             :   'TAX',
    '계속영업이익'           :   'CONTOP',
    '중단영업이익'           :   'DISCONTOP',
    '당기순이익'             :   'NETINC',
    '지배주주순이익'          :   'NETINC_1',
    '비지배주주순이익'        :   'NETINC_2',
}


DEACHA={
    '종목코드'                         : 'STKCODE',
    '날짜'                         : 'DATE',
    '보고서종류'                       : 'REPORT',
    '자산'                                      : 'Assets_Total',
    '유동자산'                                 : 'Current_Assets_Total',
    '유동자산_재고자산'                                 : 'Current_Inventory',
    '유동자산_유동생물자산'                                 : 'Current_Bio_Assets',
    '유동자산_유동금융자산'                                 : 'Current_Fin_Assets',
    '유동자산_매출채권및기타유동채권'                                 : 'Current_Receviables',
    '유동자산_당기법인세자산'                                 : 'Current_Tax_Assets',
    '유동자산_계약자산'                                 : 'Current_Entrusted_Assets',
    '유동자산_반품(환불)자산'                                 : 'Current_Returned_Goods_Assets',
    '유동자산_배출권'                                 : 'Current__Emissions_Allowance_Assets',
    '유동자산_기타유동자산'                                 : 'Other_Current_Assets',
    '유동자산_현금및현금성자산'                                 : 'Cash_and_Cash_Equivalents',
    '유동자산_매각예정비유동자산및처분자산집단'                                 : 'Current_Assets_On_Assets_For_Sale',
    '비유동자산'                                 : 'LT_Assets_Total',
    '비유동자산_유형자산'                                 : 'LT_Tangilbile_Assets',
    '비유동자산_무형자산'                                 : 'LT_Intangible_Assets',
    '비유동자산_비유동생물자산'                                 : 'LT_Bio_Assets',
    '비유동자산_투자부동산'                                 : 'LT_InveCurrent_Real_Estate',
    '비유동자산_장기금융자산'                                 : 'LT_Fin_Assets',
    '비유동자산_관계기업등지분관련투자자산'                                 : 'LT_InveCurrent_Asscoiates',
    '비유동자산_장기매출채권및기타비유동채권'                                 : 'LT_Receivables',
    '비유동자산_이연법인세자산'                                 : 'LT_Def_Income_Tax_Assets',
    '비유동자산_장기당기법인세자산'                                 : 'LT_Tax_Assets',
    '비유동자산_계약자산'                                 : 'LT_Entrusted_Assets',
    '비유동자산_반품(환불)자산'                                 : 'LT_Returned_Goods',
    '비유동자산_배출권'                                 : 'LT_Emissions_Allowance',
    '비유동자산_기타비유동자산'                                 : 'Other_LT_Assets',
    '기타금융업자산'                                 : 'Other_Fin_Assets',
    '부채'                                 : 'Liabilities_Total',
    '유동부채'                         : 'Current_Liab_Total',
    '유동부채_단기사채'                                 : 'Current_Bonds',
    '유동부채_단기차입금'                                 : 'Current_Loans',
    '유동부채_유동성장기부채'                                 : 'Current_Portion_LT_Liab',
    '유동부채_유동금융부채'                                 : 'Current_Fin_Liab',
    '유동부채_매입채무및기타유동채무'                                 : 'Current_Payables',
    '유동부채_유동종업원급여충당부채'                                 : 'Current_Emp_Benefits',
    '유동부채_기타단기충당부채'                                 : 'Current_Provisions',
    '유동부채_당기법인세부채'                                 : 'Current_Tax_Liab',
    '유동부채_계약부채'                                 : 'Current_Entrusted_Liab',
    '유동부채_반품(환불)부채'                                 : 'Current_Return_Goods_Liab',
    '유동부채_배출부채'                                 : 'Crrunt_Emission_Allowance_Liab',
    '유동부채_기타유동부채'                                 : 'Other_Current_Liab',
    '유동부채_매각예정으로분류된처분자산집단에포함된부채'                     : 'Current_Liab_On_Assets_For_Sale',
    '비유동부채'                     : 'LT_Liab_Total',
    '비유동부채_사채'                     : 'LT_Bonds',
    '비유동부채_장기차입금'                     : 'LT_Loans',
    '비유동부채_비유동금융부채'                     : 'LT_Fin_Liab',
    '비유동부채_장기매입채무및기타비유동채무'                     : 'LT_Payables',
    '비유동부채_비유동종업원급여충당부채'                     : 'LT_Emp_Benefits',
    '비유동부채_기타장기충당부채'                     : 'LT_Provisions',
    '비유동부채_이연법인세부채'                     : 'LT_Def_Incom_Tax_Liab',
    '비유동부채_장기당기법인세부채'                     : 'LT_Tax_Liab',
    '비유동부채_계약부채'                     : 'LT_Entrusted_Liab',
    '비유동부채_반품(환불)부채'                     : 'LT_Returned_Goods_Liab',
    '비유동부채_배출부채'                     : 'LT_Emissions_Allowance_Liab',
    '비유동부채_기타비유동부채'                     : 'Other_LT_Liab',
    '기타금융업부채'                     : 'Other_Fin_Liab_Total',
    '자본'                     : 'Equity_Total',
    '지배기업주주지분'                     : 'Controlling_Equity_Total',
    '지배기업주주지분_자본금'                     : 'Paid_in_Capital',
    '지배기업주주지분_신종자본증권'                     : 'Contingent_Convertible_Bonds',
    '지배기업주주지분_자본잉여금'                     : 'Capital_Surplus',
    '지배기업주주지분_기타자본'                     : 'Other_Equity',
    '지배기업주주지분_기타포괄손익누계액'                     : 'Accum_Other_Comprehensive_Incom',
    '지배기업주주지분_이익잉여금(결손금)'                     : 'Retained_Earnings',
    '비지배주주지분'                     : 'Non_Controlling_Equity_Total',
}

CASH={
    '종목코드'                         : 'STKCODE',
    '날짜'                         : 'DATE',
    '보고서종류'                       : 'REPORT',
    '영업활동현금흐름' : 'CFO_Total',
    '당기순손익' : 'Net_Income_Total',
    '법인세비용차감전계속사업이익' : 'Cont_Biz_Before_Tax',
    '현금유출이없는비용등가산' : 'Add_Exp_WO_CF_Out',
    '현금유출이없는비용등가산_퇴직급여' : 'Add_Exp_WO_CF_Out_1',
    '현금유출이없는비용등가산_종업원급여' : 'Add_Exp_WO_CF_Out_2',
    '현금유출이없는비용등가산_주식보상비' : 'Add_Exp_WO_CF_Out_3',
    '현금유출이없는비용등가산_대손상각비' : 'Add_Exp_WO_CF_Out_4',
    '현금유출이없는비용등가산_감가상각비' : 'Add_Exp_WO_CF_Out_5',
    '현금유출이없는비용등가산_무형자산상각비' : 'Add_Exp_WO_CF_Out_6',
    '현금유출이없는비용등가산_계약부채전입액' : 'Add_Exp_WO_CF_Out_7',
    '현금유출이없는비용등가산_반품(환불)부채전입액' : 'Add_Exp_WO_CF_Out_8',
    '현금유출이없는비용등가산_배출부채전입액' : 'Add_Exp_WO_CF_Out_9',
    '현금유출이없는비용등가산_충당부채전입액' : 'Add_Exp_WO_CF_Out_10',
    '현금유출이없는비용등가산_외환손실' : 'Add_Exp_WO_CF_Out_11',
    '현금유출이없는비용등가산_기타의대손상각비' : 'Add_Exp_WO_CF_Out_12',
    '현금유출이없는비용등가산_금융원가' : 'Add_Exp_WO_CF_Out_13',
    '현금유출이없는비용등가산_이자비용' : 'Add_Exp_WO_CF_Out_14',
    '현금유출이없는비용등가산_배당금지급' : 'Add_Exp_WO_CF_Out_15',
    '현금유출이없는비용등가산_매출채권처분손실' : 'Add_Exp_WO_CF_Out_16',
    '현금유출이없는비용등가산_당기손익-공정가치측정 금융자산관련손실' : 'Add_Exp_WO_CF_Out_17',
    '현금유출이없는비용등가산_금융자산처분손실' : 'Add_Exp_WO_CF_Out_18',
    '현금유출이없는비용등가산_금융자산평가손실' : 'Add_Exp_WO_CF_Out_19',
    '현금유출이없는비용등가산_금융자산손상차손' : 'Add_Exp_WO_CF_Out_20',
    '현금유출이없는비용등가산_파생상품손실' : 'Add_Exp_WO_CF_Out_21',
    '현금유출이없는비용등가산_금융부채관련손실' : 'Add_Exp_WO_CF_Out_22',
    '현금유출이없는비용등가산_사채상환손실' : 'Add_Exp_WO_CF_Out_23',
    '현금유출이없는비용등가산_재고자산감모손실' : 'Add_Exp_WO_CF_Out_24',
    '현금유출이없는비용등가산_재고자산폐기(처분)손실' : 'Add_Exp_WO_CF_Out_25',
    '현금유출이없는비용등가산_자산처분(폐기)손실' : 'Add_Exp_WO_CF_Out_26',
    '현금유출이없는비용등가산_투자자산평가손실' : 'Add_Exp_WO_CF_Out_27',
    '현금유출이없는비용등가산_자산재평가손실' : 'Add_Exp_WO_CF_Out_28',
    '현금유출이없는비용등가산_자산손상차손' : 'Add_Exp_WO_CF_Out_29',
    '현금유출이없는비용등가산_지분법관련손실' : 'Add_Exp_WO_CF_Out_30',
    '현금유출이없는비용등가산_종속기업관련손실' : 'Add_Exp_WO_CF_Out_31',
    '현금유출이없는비용등가산_관계기업관련손익' : 'Add_Exp_WO_CF_Out_32',
    '현금유출이없는비용등가산_법인세비용' : 'Add_Exp_WO_CF_Out_33',
    '현금유출이없는비용등가산_기타비용' : 'Add_Exp_WO_CF_Out_34',
    '(현금유입이없는수익등차감)' : 'Ded_Rev_WO_CF_In',
    '(현금유입이없는수익등차감)_외환이익' : 'Ded_Rev_WO_CF_In_1',
    '(현금유입이없는수익등차감)_대손충당금환입액' : 'Ded_Rev_WO_CF_In_2',
    '(현금유입이없는수익등차감)_금융수익' : 'Ded_Rev_WO_CF_In__3',
    '(현금유입이없는수익등차감)_이자수익' : 'Ded_Rev_WO_CF_In_4',
    '(현금유입이없는수익등차감)_배당금수익' : 'Ded_Rev_WO_CF_In_5',
    '(현금유입이없는수익등차감)_매출채권처분이익' : 'Ded_Rev_WO_CF_In_6',
    '(현금유입이없는수익등차감)_당기손익-공정가치측정 금융자산관련이익' : 'Ded_Rev_WO_CF_In_7',
    '(현금유입이없는수익등차감)_금융자산처분이익' : 'Ded_Rev_WO_CF_In_8',
    '(현금유입이없는수익등차감)_금융자산평가이익' : 'Ded_Rev_WO_CF_In_9',
    '(현금유입이없는수익등차감)_금융자산손상차손환입' : 'Ded_Rev_WO_CF_In_10',
    '(현금유입이없는수익등차감)_파생상품이익' : 'Ded_Rev_WO_CF_In_11',
    '(현금유입이없는수익등차감)_금융부채관련이익' : 'Ded_Rev_WO_CF_In_12',
    '(현금유입이없는수익등차감)_사채상환이익' : 'Ded_Rev_WO_CF_In_13',
    '(현금유입이없는수익등차감)_퇴직급여충당부채환입액' : 'Ded_Rev_WO_CF_In_14',
    '(현금유입이없는수익등차감)_계약부채환입액' : 'Ded_Rev_WO_CF_In_15',
    '(현금유입이없는수익등차감)_반품(환불)부채환입액' : 'Ded_Rev_WO_CF_In_16',
    '(현금유입이없는수익등차감)_배출부채환입액' : 'Ded_Rev_WO_CF_In_17',
    '(현금유입이없는수익등차감)_충당부채환입액' : 'Ded_Rev_WO_CF_In_18',
    '(현금유입이없는수익등차감)_주식보상비환입' : 'Ded_Rev_WO_CF_In_19',
    '(현금유입이없는수익등차감)_재고자산감모손실환입' : 'Ded_Rev_WO_CF_In_20',
    '(현금유입이없는수익등차감)_재고자산폐기(처분)이익' : 'Ded_Rev_WO_CF_In_21',
    '(현금유입이없는수익등차감)_자산처분(폐기)이익' : 'Ded_Rev_WO_CF_In_22',
    '(현금유입이없는수익등차감)_투자자산평가이익' : 'Ded_Rev_WO_CF_In_23',
    '(현금유입이없는수익등차감)_자산재평가이익' : 'Ded_Rev_WO_CF_In_24',
    '(현금유입이없는수익등차감)_자산손상차손환입' : 'Ded_Rev_WO_CF_In_25',
    '(현금유입이없는수익등차감)_지분법관련이익' : 'Ded_Rev_WO_CF_In_26',
    '(현금유입이없는수익등차감)_종속회사관련이익' : 'Ded_Rev_WO_CF_In_27',
    '(현금유입이없는수익등차감)_관계기업관련손익' : 'Ded_Rev_WO_CF_In_28',
    '(현금유입이없는수익등차감)_법인세수익' : 'Ded_Rev_WO_CF_In_29',
    '(현금유입이없는수익등차감)_기타수익' : 'Ded_Rev_WO_CF_In_30',
    '영업활동으로인한자산부채변동(운전자본변동)' : 'Chg_Working_Capital',
    '영업활동으로인한자산부채변동(운전자본변동)_자산의감소(증가)' : 'Chg_Working_Capital_1',
    '영업활동으로인한자산부채변동(운전자본변동)_부채의증가(감소)' : 'Chg_Working_Capital_2',
    '영업활동으로인한자산부채변동(운전자본변동)_정부보조금등의변동' : 'Chg_Working_Capital_3',
    '영업활동으로인한자산부채변동(운전자본변동)_기타운전자본의변동' : 'Chg_Working_Capital_4',
    '영업에서창출된현금흐름' : 'CFO',
    '기타영업활동으로인한현금흐름' : 'Other_CFO',
    '기타영업활동으로인한현금흐름_이자수입' : 'Other_CFO_1',
    '기타영업활동으로인한현금흐름_이자지급(-)' : 'Other_CFO_2',
    '기타영업활동으로인한현금흐름_배당금수입' : 'Other_CFO_3',
    '기타영업활동으로인한현금흐름_배당금지급(-)' : 'Other_CFO_4',
    '기타영업활동으로인한현금흐름_법인세환입' : 'Other_CFO_5',
    '기타영업활동으로인한현금흐름_법인세납부(-)' : 'Other_CFO_6',
    '기타영업활동으로인한현금흐름_중단영업관련현금흐름' : 'Other_CFO_7',
    '투자활동으로인한현금흐름' : 'CFI_Total',
    '투자활동으로인한현금유입액' : 'CFI_In',
    '투자활동으로인한현금유입액_유동금융자산의감소' : 'CFI_In_1',
    '투자활동으로인한현금유입액_장기금융상품의감소' : 'CFI_In_2',
    '투자활동으로인한현금유입액_매도가능금융자산의감소' : 'CFI_In_3',
    '투자활동으로인한현금유입액_만기보유금융자산의감소' : 'CFI_In_4',
    '투자활동으로인한현금유입액_장기대여금의감소' : 'CFI_In_5',
    '투자활동으로인한현금유입액_파생상품의변동' : 'CFI_In_6',
    '투자활동으로인한현금유입액_기타비유동금융자산의감소' : 'CFI_In_7',
    '투자활동으로인한현금유입액_관계기업등지분관련투자자산의감소' : 'CFI_In_8',
    '투자활동으로인한현금유입액_유형자산의감소' : 'CFI_In_9',
    '투자활동으로인한현금유입액_무형자산의감소' : 'CFI_In_10',
    '투자활동으로인한현금유입액_생물자산의감소' : 'CFI_In_11',
    '투자활동으로인한현금유입액_투자부동산의감소' : 'CFI_In_12',
    '투자활동으로인한현금유입액_기타투자활동으로인한현금유입액' : 'CFI_In_13',
    '(투자활동으로인한현금유출액)' : 'CFI_Out',
    '(투자활동으로인한현금유출액)_유동금융자산의증가' : 'CFI_Out_1',
    '(투자활동으로인한현금유출액)_장기금융상품의증가' : 'CFI_Out_2',
    '(투자활동으로인한현금유출액)_매도가능금융자산의증가' : 'CFI_Out_3',
    '(투자활동으로인한현금유출액)_만기보유금융자산의증가' : 'CFI_Out_4',
    '(투자활동으로인한현금유출액)_장기대여금의증가' : 'CFI_Out_5',
    '(투자활동으로인한현금유출액)_파생상품의변동' : 'CFI_Out_6',
    '(투자활동으로인한현금유출액)_기타비유동금융자산의증가' : 'CFI_Out_7',
    '(투자활동으로인한현금유출액)_관계기업등지분관련투자자산의증가' : 'CFI_Out_8',
    '(투자활동으로인한현금유출액)_유형자산의증가' : 'CFI_Out_9',
    '(투자활동으로인한현금유출액)_무형자산의증가' : 'CFI_Out_10',
    '(투자활동으로인한현금유출액)_생물자산의증가' : 'CFI_Out_11',
    '(투자활동으로인한현금유출액)_투자부동산의증가' : 'CFI_Out_12',
    '(투자활동으로인한현금유출액)_기타투자활동으로인한현금유출액' : 'CFI_Out_13',
    '기타투자활동으로인한현금흐름' : 'Other_CFI',
    '기타투자활동으로인한현금흐름_이자수입' : 'Other_CFI_1',
    '기타투자활동으로인한현금흐름_이자지급(-)' : 'Other_CFI_2',
    '기타투자활동으로인한현금흐름_배당금수입' : 'Other_CFI_3',
    '기타투자활동으로인한현금흐름_배당금지급(-)' : 'Other_CFI_4',
    '기타투자활동으로인한현금흐름_법인세환입' : 'Other_CFI_5',
    '기타투자활동으로인한현금흐름_법인세납부(-)' : 'Other_CFI_6',
    '기타투자활동으로인한현금흐름_중단영업관련현금흐름' : 'Other_CFI_7',
    '재무활동으로인한현금흐름' : 'CFF_Total',
    '재무활동으로인한현금유입액' : 'CFF_In',
    '재무활동으로인한현금유입액_사채의증가' : 'CFF_In_1',
    '재무활동으로인한현금유입액_차입금의증가' : 'CFF_In_2',
    '재무활동으로인한현금유입액_미지급금의증가' : 'CFF_In_3',
    '재무활동으로인한현금유입액_유동성장기부채의증가' : 'CFF_In_4',
    '재무활동으로인한현금유입액_기타금융부채의증가' : 'CFF_In_5',
    '재무활동으로인한현금유입액_기타부채의증가' : 'CFF_In_6',
    '재무활동으로인한현금유입액_유상증자' : 'CFF_In_7',
    '재무활동으로인한현금유입액_자기주식의처분' : 'CFF_In_8',
    '재무활동으로인한현금유입액_주식매입선택권의행사' : 'CFF_In_9',
    '재무활동으로인한현금유입액_자본구성항목의증가' : 'CFF_In_10',
    '재무활동으로인한현금유입액_기타재무활동으로인한현금유입액' : 'CFF_In_11',
    '(재무활동으로인한현금유출액)' : 'CFF_Out',
    '(재무활동으로인한현금유출액)_사채의감소' : 'CFF_Out_1',
    '(재무활동으로인한현금유출액)_차입금의감소' : 'CFF_Out_2',
    '(재무활동으로인한현금유출액)_미지급금의감소' : 'CFF_Out_3',
    '(재무활동으로인한현금유출액)_유동성장기부채의감소' : 'CFF_Out_4',
    '(재무활동으로인한현금유출액)_기타금융부채의감소' : 'CFF_Out_5',
    '(재무활동으로인한현금유출액)_기타부채의감소' : 'CFF_Out_6',
    '(재무활동으로인한현금유출액)_유상감자' : 'CFF_Out_7',
    '(재무활동으로인한현금유출액)_자기주식의취득' : 'CFF_Out_8',
    '(재무활동으로인한현금유출액)_자본구성항목의감소' : 'CFF_Out_9',
    '(재무활동으로인한현금유출액)_기타재무활동으로인한현금유출액' : 'CFF_Out_10',
    '기타재무활동으로인한현금흐름' : 'Other_CFF',
    '기타재무활동으로인한현금흐름_이자수입' : 'Other_CFF_1',
    '기타재무활동으로인한현금흐름_자지급(-)' : 'Other_CFF_2',
    '기타재무활동으로인한현금흐름_배당금수입' : 'Other_CFF_3',
    '기타재무활동으로인한현금흐름_배당금지급(-)' : 'Other_CFF_4',
    '기타재무활동으로인한현금흐름_법인세환입' : 'Other_CFF_5',
    '기타재무활동으로인한현금흐름_법인세납부(-)' : 'Other_CFF_6',
    '기타재무활동으로인한현금흐름_중단영업관련현금흐름' : 'Other_CFF_7',
    '영업투자재무활동기타현금흐름' : 'Other_CF',
    '연결범위변동으로인한현금의증가' : 'Chg_CF_Consolidation',
    '환율변동효과' : 'Forex_Effect',
    '현금및현금성자산의증가' : 'Chg_Cash_and_Cash_Equivalents',
    '기초현금및현금성자산' : 'Cash_and_Cash_Equivalents',
    '기말현금및현금성자산' : 'Cash_and_Cash_Equivalents_End',
    
}

def get_tableSQL(table, JamuCode):
    col = None
    sql =''
    if JamuCode =='sonik':
        col = SONIK.values()
    elif JamuCode == 'deacha':
        col = DEACHA.values()
    else:
        col = CASH.values()
    sql = 'create table ' + table +'('
    sql += 'STKCODE varchar(10), DATE varchar(10), REPORT varchar(3), '
    for i in list(col)[3:]:
        sql += i + ' bigint'+','
    sql = sql[0:-1] +');'
    
    return sql

if __name__=='__main__':
    conn = pymysql.connect(host='localhost', user='root', 
                       password='root', db='stock', charset='utf8')
    curs = conn.cursor()
    
    curs.execute(get_tableSQL('sonik','sonik'))
    curs.execute(get_tableSQL('deacha','deacha'))
    curs.execute(get_tableSQL('cash','cash'))
    
    curs.close()